export const TWEET_CREATE_REQUEST = 'TWEET_CREATE_REQUEST';
export const TWEET_CREATE_SUCCESS = 'TWEET_CREATE_SUCCESS';
export const TWEET_CREATE_FAILURE = 'TWEET_CREATE_FAILURE';

export const TWEET_DELETE_REQUEST = 'TWEET_DELETE_REQUEST';
export const TWEET_DELETE_SUCCESS = 'TWEET_DELETE_SUCCESS'; 
export const TWEET_DELETE_FAILURE = 'TWEET_DELETE_FAILURE';

export const GET_ALL_TWEETS_REQUEST = 'GET_ALL_TWEETS_REQUEST';
export const GET_ALL_TWEETS_SUCCESS = 'GET_ALL_TWEETS_SUCCESS'; 
export const GET_ALL_TWEETS_FAILURE = 'GET_ALL_TWEETS_FAILURE';

export const GET_USERS_TWEETS_REQUEST = 'GET_USERS_TWEETS_REQUEST';
export const GET_USERS_TWEETS_SUCCESS = 'GET_USERS_TWEETS_SUCCESS'; 
export const GET_USERS_TWEETS_FAILURE = 'GET_USERS_TWEETS_FAILURE';


//user id and how certain user have likeed a tweet 
export const USERS_LIKE_TWEET_REQUEST = 'USERS_LIKE_TWEET_REQUEST';
export const USERS_LIKE_TWEET_SUCCESS = 'USERS_LIKE_TWEET_SUCCESS'; 
export const USERS_LIKE_TWEET_FAILURE = 'USERS_LIKE_TWEET_FAILURE';


//all like tweets of a user
export const LIKE_TWEETS_REQUEST = 'LIKE_TWEETS_REQUEST';
export const LIKE_TWEETS_SUCCESS = 'LIKE_TWEETS_SUCCESS'; 
export const LIKE_TWEETS_FAILURE = 'LIKE_TWEETS_FAILURE';

export const FIND_TWEET_BY_ID_REQUEST = 'FIND_TWEET_BY_ID_REQUEST';
export const FIND_TWEET_BY_ID_SUCCESS = 'FIND_TWEET_BY_ID_SUCCESS'; 
export const FIND_TWEET_BY_ID_FAILURE = 'FIND_TWEET_BY_ID_FAILURE';

export const REPLY_TWEETS_REQUEST = 'REPLY_TWEETS_REQUEST';
export const REPLY_TWEETS_SUCCESS = 'REPLY_TWEETS_SUCCESS'; 
export const REPLY_TWEETS_FAILURE = 'REPLY_TWEETS_FAILURE';

export const RETWEET_REQUEST = 'RETWEET_REQUEST';
export const RETWEET_SUCCESS = 'RETWEET_SUCCESS'; 
export const RETWEET_FAILURE = 'RETWEET_FAILURE';